name: Test smart contracts
run-name: Testing main Poor Apes smart contract
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
